<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icons8-files-48.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icons8-files-48.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FrmEditStudent.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
